import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Container } from "@mui/material";
import HeaderLayout from "@/component/header";
import FooterLayout from "@/component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body style={{ margin: "0", padding: "0" }}>
        <HeaderLayout />
        <Container>{children}</Container>
        <FooterLayout />
      </body>
    </html>
  );
}
